#!/bin/bash

# jupyter nbextension     enable --py --sys-prefix appmode
# jupyter serverextension enable --py --sys-prefix appmode
pip install gekko
pip install seeq
pip install keras-tuner==1.0.4
pip install tensorflow>=2.1
